### ISSUE TITLE
[BUG] PA Profile missing 

### ISSUE THREAD

**Issue by DC1RS** [mi0bot/OpenHPSDR-Thetis#99]
After update to 2.10.3.7 Beta 1 the PA Profile for HL2 is missing:

![21037_PA Gain](https://github.com/user-attachments/assets/6daa6176-f0e0-4121-a4ca-0c65cf358351)

Dropdown menue for selection is empty.
Reverting back to 2.10.3.6 HL2 PA Profile is available again.

 - OS: Windows 11
 - Thetis version: 2.10.3.7 Beta 1

**Comment by pharmaw** [comment]
Hitted New, Written Default as name then thetis recover the old one.

**Comment by mi0bot** [comment]
There is an issue with PA profiles due to enumeration changing within the Thetis code. There will be a fix of sorts in the next release, but it might not be perfect and require redefinition of the profiles.
